import Head from "next/head"
import styles from '../styles/styles.module.css'

const Header = ({title}) => {
    return (
        <div>
            <Head>
                <title>{title}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <header>
                <h1 className={styles.textCenter}>todolist in next.js</h1>
            </header>    
        </div>
    )
}

export default Header